Repository Kruacent/Kruacent-Exiled, pull requests merged in 2024-12, with the labels that each got.

#12 [NEW ITEM] The Defibrilator
  KruacentE.Items/Items/Defibrilator.cs
Labels: new feature

#17 Misc
  KruacentE.Misc/Config.cs
  KruacentE.Misc/MainPlugin.cs
  KruacentE.Misc/README.md
  KruacentE.Misc/ServerHandler.cs
Labels: new feature

#18 Add all GlobalEvents
  KruacentE.BlackoutNDoor/API/Features/Controller.cs
  KruacentE.BlackoutNDoor/Handlers/ServerHandler.cs
  KruacentE.BlackoutNDoor/MainPlugin.cs
  KruacentE.GlobalEventFramework/GEFE.Examples/Config.cs
  KruacentE.GlobalEventFramework/GEFE.Examples/GE/Blitz.cs
  KruacentE.GlobalEventFramework/GEFE.Examples/GE/Impostor.cs
  KruacentE.GlobalEventFramework/GEFE.Examples/GE/KIWIS.cs
  KruacentE.GlobalEventFramework/GEFE.Examples/GE/R.cs
  KruacentE.GlobalEventFramework/GEFE.Examples/GE/RandomSpawn.cs
  KruacentE.GlobalEventFramework/GEFE.Examples/GE/Shuffle.cs
  KruacentE.GlobalEventFramework/GEFE.Examples/GE/Speed.cs
  KruacentE.GlobalEventFramework/GEFE.Examples/GE/SystemMalfunction.cs
  KruacentE.GlobalEventFramework/GEFE.Examples/MainPlugin.cs
  KruacentE.GlobalEventFramework/GEFE/API/Features/GlobalEvent.cs
  KruacentE.GlobalEventFramework/GEFE/API/Utils/Coroutine.cs
  KruacentE.GlobalEventFramework/GEFE/Commands/List.cs
  KruacentE.GlobalEventFramework/GEFE/Commands/ParentCommandGEFE.cs
  KruacentE.GlobalEventFramework/GEFE/Handlers/ServerHandler.cs
  KruacentE.GlobalEventFramework/GEFExiled.csproj
  KruacentE.GlobalEventFramework/GEFExiled.sln
  KruacentE.GlobalEventFramework/MainPlugin.cs
Labels: new Global Event

#19 [GE] Impostor Fix.
  KruacentE.GlobalEventFramework/GEFE.Examples/GE/Impostor.cs
  KruacentE.GlobalEventFramework/GEFE/Handlers/ServerHandler.cs
  KruacentE.GlobalEventFramework/MainPlugin.cs
Labels: bug
